[2024-02-25T20:25:40.978+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-25T19:02:00+00:00 [queued]>
[2024-02-25T20:25:41.061+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-25T19:02:00+00:00 [queued]>
[2024-02-25T20:25:41.062+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-25T20:25:42.442+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): get_exchange_data> on 2024-02-25 19:02:00+00:00
[2024-02-25T20:25:42.480+0000] {standard_task_runner.py:60} INFO - Started process 2277 to run task
[2024-02-25T20:25:42.506+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'get_exchange_data', 'scheduled__2024-02-25T19:02:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmp1wd6xqow']
[2024-02-25T20:25:42.521+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask get_exchange_data
[2024-02-25T20:25:42.906+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-25T19:02:00+00:00 [running]> on host f5283f9a0a92
[2024-02-26T06:29:03.695+0000] {local_task_job_runner.py:211} ERROR - Heartbeat time limit exceeded!
[2024-02-26T06:29:03.755+0000] {process_utils.py:131} INFO - Sending 15 to group 2277. PIDs of all processes in the group: [2277]
[2024-02-26T06:29:03.831+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2277
[2024-02-26T06:29:03.842+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-26T06:29:04.198+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2469, in _execute_task_with_callbacks
    RenderedTaskInstanceFields.write(rtif)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/retries.py", line 91, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/retries.py", line 100, in wrapped_function
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py", line 192, in write
    session.merge(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1569, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 532, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 567, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 809, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 464, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 499, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 3403, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 765, in create_for_statement
    self._setup_for_generate()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 879, in _setup_for_generate
    strategy(self, *rec[1:])
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 2338, in _create_eager_join
    eagerjoin = orm_util._ORMJoin(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/util.py", line 1755, in __init__
    ) = prop._create_joins(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2573, in _create_joins
    ) = self._join_condition.join_targets(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 3629, in join_targets
    primaryjoin = primary_aliasizer.traverse(primaryjoin)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 619, in traverse
    return replacement_traverse(obj, self.__traverse_options__, replace)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 848, in replacement_traverse
    obj = clone(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 844, in clone
    newelem._copy_internals(clone=clone, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/traversals.py", line 839, in _copy_internals
    result = meth(attrname, self, obj, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/traversals.py", line 856, in visit_clauseelement_list
    return [clone(clause, **kw) for clause in element]
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/traversals.py", line 856, in <listcomp>
    return [clone(clause, **kw) for clause in element]
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 827, in clone
    newelem = replace(elem)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 615, in replace
    e = v.replace(elem)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/util.py", line 914, in replace
    return self._corresponding_column(col, True)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/util.py", line 839, in _corresponding_column
    newcol = self.selectable.corresponding_column(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 226, in corresponding_column
    return self.exported_columns.corresponding_column(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/base.py", line 1396, in corresponding_column
    target_set = column.proxy_set
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-02-26T06:29:11.823+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=exchange_trade_data, task_id=get_exchange_data, execution_date=20240225T190200, start_date=20240225T202540, end_date=20240226T062911
[2024-02-26T06:29:13.919+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 36 for task get_exchange_data (Task received SIGTERM signal; 2277)
[2024-02-26T06:29:14.205+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2277, status='terminated', exitcode=1, started='20:25:41') (2277) terminated with exit code 1
