[2024-03-01T15:22:31.116+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.write_to_motherduck_from_data_frame manual__2024-03-01T15:21:20.031768+00:00 [queued]>
[2024-03-01T15:22:31.162+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.write_to_motherduck_from_data_frame manual__2024-03-01T15:21:20.031768+00:00 [queued]>
[2024-03-01T15:22:31.174+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-01T15:22:31.783+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): write_to_motherduck_from_data_frame> on 2024-03-01 15:21:20.031768+00:00
[2024-03-01T15:22:31.801+0000] {standard_task_runner.py:60} INFO - Started process 3617 to run task
[2024-03-01T15:22:31.811+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'write_to_motherduck_from_data_frame', 'manual__2024-03-01T15:21:20.031768+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmpohyjxcq1']
[2024-03-01T15:22:31.816+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask write_to_motherduck_from_data_frame
[2024-03-01T15:22:32.004+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.write_to_motherduck_from_data_frame manual__2024-03-01T15:21:20.031768+00:00 [running]> on host 11bab81981d3
[2024-03-01T15:22:32.413+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='write_to_motherduck_from_data_frame' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T15:21:20.031768+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-01T15:21:20.031768+00:00'
[2024-03-01T15:23:04.315+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/exchange.py", line 79, in write_to_motherduck_from_data_frame
    con = db.connect(f'md:{database_name}?motherduck_token={motherduck_token}')
duckdb.duckdb.InvalidInputException: Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.duckdb_extension" threw an exception: "Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.v1.15.18.duckdb_extension" threw an exception: "IO Error: RPC 'GET_WELCOME_PACK' failed: Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections (UNAUTHENTICATED, request id: '818dfa9c-9c0e-4270-a1f7-ab2ae1664323')""
[2024-03-01T15:23:04.352+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=exchange_trade_data, task_id=write_to_motherduck_from_data_frame, execution_date=20240301T152120, start_date=20240301T152231, end_date=20240301T152304
[2024-03-01T15:23:04.412+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task write_to_motherduck_from_data_frame (Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.duckdb_extension" threw an exception: "Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.v1.15.18.duckdb_extension" threw an exception: "IO Error: RPC 'GET_WELCOME_PACK' failed: Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections (UNAUTHENTICATED, request id: '818dfa9c-9c0e-4270-a1f7-ab2ae1664323')""; 3617)
[2024-03-01T15:23:04.474+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-01T15:23:04.568+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
